// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmNUKxYP9o16xWKCLQeUcCNU4knwBomA',
    appId: '1:221694384789:web:a217a43cfe4bb3092e999c',
    messagingSenderId: '221694384789',
    projectId: 'calendarappproject-68efd',
    authDomain: 'calendarappproject-68efd.firebaseapp.com',
    storageBucket: 'calendarappproject-68efd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnISEjDLPstkD8Ctcm60Tyq06drYY9ZA',
    appId: '1:221694384789:android:f0b5d2ab58f4a0b72e999c',
    messagingSenderId: '221694384789',
    projectId: 'calendarappproject-68efd',
    storageBucket: 'calendarappproject-68efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeYQHavQQlH32povvWgVhba07KvX9XMJM',
    appId: '1:221694384789:ios:4d29fa48b2d0a0572e999c',
    messagingSenderId: '221694384789',
    projectId: 'calendarappproject-68efd',
    storageBucket: 'calendarappproject-68efd.firebasestorage.app',
    iosBundleId: 'com.example.calendarAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeYQHavQQlH32povvWgVhba07KvX9XMJM',
    appId: '1:221694384789:ios:4d29fa48b2d0a0572e999c',
    messagingSenderId: '221694384789',
    projectId: 'calendarappproject-68efd',
    storageBucket: 'calendarappproject-68efd.firebasestorage.app',
    iosBundleId: 'com.example.calendarAp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmNUKxYP9o16xWKCLQeUcCNU4knwBomA',
    appId: '1:221694384789:web:8daa9670413ad6b52e999c',
    messagingSenderId: '221694384789',
    projectId: 'calendarappproject-68efd',
    authDomain: 'calendarappproject-68efd.firebaseapp.com',
    storageBucket: 'calendarappproject-68efd.firebasestorage.app',
  );
}
